FizzBuzzApp/FizzBuzzApp/Models/FizzBuzzModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzBuzzApp.Models
{
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "* Input Required")]
        [Display(Name = "Please Enter Number")]
        [Range(1, 1000, ErrorMessage = "* The input value must be between 1 and 1000")]
        public int Number { get; set; }

        public IPagedList<string> FizzBuzzList { get; set; }

        public int? Page { get; set; }
    }
}

FizzBuzzApp/FizzBuzzApp/Controllers/FizzBuzzController.cs
using FizzBuzzApp.Models;
using FizzBuzzService.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FizzBuzzApp.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService _fizzBuzzService;
        private const int PageSize = 20;
        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            _fizzBuzzService = fizzBuzzService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ModelState.Clear();
            var emptyModel = new FizzBuzzModel() { FizzBuzzList = new PagedList<string>(new List<string>(), 1, PageSize) };
            return View("Index", emptyModel);
        }

        [HttpGet]
        public ActionResult GetList(FizzBuzzModel fizzBuzzModel)
        {
            if (ModelState.IsValid)
            {
                var fizzbuzzList = _fizzBuzzService.GetFizzBuzzList(fizzBuzzModel.Number);
                if ((fizzBuzzModel.Page ?? 1) * PageSize > fizzbuzzList.Count())
                {
                    fizzBuzzModel.Page = GetMaxPageNumber(fizzbuzzList.Count());
                }
                fizzBuzzModel.FizzBuzzList = fizzbuzzList.ToPagedList(fizzBuzzModel.Page ?? 1, PageSize);
            }
            return View("Index", fizzBuzzModel);
        }

        private int GetMaxPageNumber(double totalItems)
        {
            var mxPageSize = totalItems / PageSize;
            return (int)Math.Ceiling(mxPageSize);
        }
    }
}

FizzBuzzApp/FizzBuzzApp/Views/FizzBuzz/Index.cshtml
@{
    Layout = null;
}
@model FizzBuzzApp.Models.FizzBuzzModel
@using System.Web.Optimization
@using PagedList.Mvc;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div>
        <div>
            <h2>Fizz Buzz Application</h2>
            @using (@Html.BeginForm("GetList", "FizzBuzz", FormMethod.Get))
            {
                @Html.ValidationSummary(true);
                @Html.LabelFor(m => m.Number);
                @Html.TextBoxFor(m => m.Number);
                @Html.ValidationMessageFor(m => m.Number);
                <input type="submit" value="Get List" />
            }
        </div>
        <div>
            @if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Any())
            { 
                <ul>
                    @foreach (var item in Model.FizzBuzzList)
                    {
                        var className = item.Contains(" ") ? string.Empty : item;
                        <li class="@className">@item</li>
                    }
                </ul>
                <p>
                    @Html.PagedListPager((Model.FizzBuzzList), page => Url.Action("GetList", new { Page = page, Number = Model.Number }), PagedList.Mvc.PagedListRenderOptions.ClassicPlusFirstAndLast)
                </p>
            }
        </div>
    </div>
</body>
</html>